

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PdpApi
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class PDPEntities : DbContext
{
    public PDPEntities()
        : base("name=PDPEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Country_LU> Country_LU { get; set; }

    public virtual DbSet<PestCode_LU> PestCode_LU { get; set; }

    public virtual DbSet<SampleData> SampleDatas { get; set; }

    public virtual DbSet<ResultsData> ResultsDatas { get; set; }


    [DbFunction("PDPEntities", "get_pdp_result_tbl")]
    public virtual IQueryable<get_pdp_result_tbl_Result> get_pdp_result_tbl(Nullable<int> start_offset, Nullable<int> numb_rows)
    {

        var start_offsetParameter = start_offset.HasValue ?
            new ObjectParameter("start_offset", start_offset) :
            new ObjectParameter("start_offset", typeof(int));


        var numb_rowsParameter = numb_rows.HasValue ?
            new ObjectParameter("numb_rows", numb_rows) :
            new ObjectParameter("numb_rows", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<get_pdp_result_tbl_Result>("[PDPEntities].[get_pdp_result_tbl](@start_offset, @numb_rows)", start_offsetParameter, numb_rowsParameter);
    }

}

}

