//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdpApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDPEntities : DbContext
    {
        public PDPEntities()
            : base("name=PDPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country_LU> Country_LU { get; set; }
        public virtual DbSet<PestCode_LU> PestCode_LU { get; set; }
        public virtual DbSet<SampleData> SampleDatas { get; set; }
        public virtual DbSet<ResultsData> ResultsDatas { get; set; }
    }
}
